### ISSUE TITLE
Lexstat automated cognate clustering with asjp data is inconsistent

### ISSUE THREAD

**Issue by erathorn** [lingpy/lingpy#169] opened 2015-08-18 08:19 UTC
The following workflow with the actual version of lingpy does not return the expected results:

    import lingpy
    lingpy.rc(schema="asjp")
    cognates = lingpy.LexStat("wordlist.wl", check=True)
    cognates.get_scorer()
    cognates.pickle()
    cognates.cluster(method="lexstat",threshold=0.3, verbose=False)
    cognates.output("csv")

Instead of proper cognate clusters each word is clustered in its own cognate class. The inputfile looks like this, but with more items per:

     ID	concept	ipa	doculect
     5425	Abend::N	swar	FRA
     5425	Abend::N	sware	FRA
     5426	Abend::N	sear3	RON
     5427	Abend::N	ivniN	ENG
     5428	Abend::N	noyt3	POR
     5428	Abend::N	tardi5a	POR
     5429	Abend::N	afd3n	DAN

**Comment by xrotwang** [comment] 2015-08-18 08:22
@erathorn Does "actual version" mean installed from `HEAD` of the repsoitory?

**Comment by erathorn** [comment] 2015-08-18 08:23
I used the version which I checked out yesterday.

**Comment by xrotwang** [comment] 2015-08-18 08:39
Hm. Looks like I broke this functionality when refactoring LexStat. Could you try
```
git checkout 38f03f50f78044f45c7240bd7d0ef0022cd85e6c
```
This should update your checkout to the commit before my changes.

**Comment by xrotwang** [comment] 2015-08-18 08:42
Ok, so by now I managed to identify the breaking commit: https://github.com/lingpy/lingpy/commit/ec76e60eb83c8bac80051b27afc2850943a672c9

**Comment by xrotwang** [comment] 2015-08-18 09:19
Just merged #170 rolling back the breaking changes.

@erathorn could you confirm?

**Comment by erathorn** [comment] 2015-08-18 10:14
@xrotwang This has not solved the issue.

**Comment by xrotwang** [comment] 2015-08-18 10:21
@erathorn maybe the pickled data is getting in the way, i.e. preventing recomputation of the scores. Could you rename the wordlist file, forcing a new computation?

**Comment by xrotwang** [comment] 2015-08-18 10:55
@erathorn I noticed your input file seems to have non-unique IDs. @LinguList Could this be the source of the problem?

**Comment by xrotwang** [comment] 2015-08-18 11:42
Going back to Nov. 2014 I still get the same results, i.e. all forms ending up in separate cognate sets. So this has not changed recently.

**Comment by erathorn** [comment] 2015-08-18 11:43
@xrotwang @LinguList I corrected the non-unique ids and i forced a new computation by renaming the input file. Both corrections did not solve the problem.

**Comment by xrotwang** [comment] 2015-08-18 18:16
It seems you chose the threshold too low. With a higher threshold I get:
```python
>>> lex = LexStat({
            0: ['ID', 'concept', 'ipa', 'doculect'],
            1: ['5424', 'Abend::N', 'swar', 'FRA'],
            2: ['5425', 'Abend::N', 'sware', 'FRA'],
            3: ['5426', 'Abend::N', 'sear3', 'RON'],
            4: ['5427', 'Abend::N', 'ivniN', 'ENG'],
            5: ['5428', 'Abend::N', 'noyt3', 'POR'],
            6: ['5429', 'Abend::N', 'tardi5a', 'POR'],
            7: ['5430', 'Abend::N', 'afd3n', 'DAN'],
        })
>>> lex.cluster(method='lexstat', threshold=0.8, ref='cogid')
>>> lex.get_entries('cogid')
[[1, 2, 3, 4, 5], [0, 0, 3, 3, 0]]
>>> lex.get_entries('id')
[['5430', '5427', '5424', '5428', '5426'], [0, 0, '5425', '5429', 0]]
```
So items 5424, 5425 and 5429 get assigned to the same cognate cluster.

**Comment by erathorn** [comment] 2015-08-18 18:46
@xrotwang Thanks, I will try this. However, this is not the behavior I expected. I thought a lower threshold would make it easier to cluster words together.

**Comment by erathorn** [comment] 2015-08-19 10:20
@xrotwang the threshold of 0.8 works fine for me. Thanks for the help.

**Comment by LinguList** [comment] 2015-08-19 13:20
Allright, first of all: for method="lexstat", take a threshold between 0.5 and 0.7. This is usually yielding satisfying results.

Furthermore, the problem does NOT occur, if you do not use the defaults in the get_scorer method, but explicitly use the following methods:

```python
>>> lex.get_scorer(method='shuffle', preprocessing=False)
```

So the error probably lies in the preprocessing method and eventually the shuffling procedure, but I guess it's preprocessing (which builds an initial simple cluster-analysis using some defaults in order to get the attested distribution). 

Here's the relevant line in LingPy.lexstat (502f):
```python
        if kw['preprocessing']:
            if kw['ref'] not in self.header:
                self.cluster(
                        method=kw['preprocessing_method'],
                        threshold=kw['preprocessing_threshold'],
                        gop = kw['gop'],
                        cluster_method=kw['cluster_method'],
                        ref=kw['ref']
                        )
```

It is quite likely that the pre-processing fails to select ANY good candidates for cognates (due to whatever reasons), or that it uses some sound-class model which is not intended to be used for ASJP-Sound-Class-Strings.

I'll look into that soon. For the meantime, please use the technique as specified, since this definitely works (and preprocessing doesn't really make a difference, in my experience).

**Comment by LinguList** [comment] 2015-08-19 16:33
I am getting confused now, since I ran the script another time with both preprocessing=False and True and method="markov" and "shuffle" both in Python 2 and Python 3 and it always yields results in expected range. So maybe this bug is no bug anymore? 

To reproduce, just check:

```python
>>> from lingpy import *
>>> rc(schema='asjp')
>>> lex = LexStat("data.tsv")
>>> lex.get_scorer(method='markov', preprocessing=True, runs=100) #runs=100 for faster checking, vary also markov with shuffle and True with False
>>> lex.cluster(method="lexstat", threshold=0.6)
>>> lex.lexstatid[0] # check for first line, if cognate ids are partially identical, the behaviour is expected
```

I don't get any buggish behaviour anymore. So @erathorn , please could you re-check with the latest version and eventually close this bug?

BTW, the line 

```python

>>> etym_dict = cognates.get_etymdict(ref='lexstatid', entry='', loans=False)
```
in @erathorn's script is bad, it should be:

```python
>>> etym_dict = cognates.get_etymdict(ref='lexstatid')
```

First, you don't need to set loans, since there are no loans in the data (all cogids are positive, since lexstat doesn't check for loans). Second, the entry keyword refers to the column, and you don't have a column which is an empty string, so you either specify a value, like entry="ipa" (ipa-column), or you get an ID instead.

Furthermore, if you want to have the data in alignmed form, the recommended way is the following:

```python

# after having calculated the cogids
>>> alm = Alignments(lex, ref="lexstatid") # lex is here the lexstat object, which you called "cognates", ref specifies the column in which you store the cognate ids)
>>> alm.align()
>>> alm.output('tsv', filename='alignments', ignore='all')
```
This will write another wordlist file with alignments being all placed in an additional column. From here, it is much easier to write all alignments to your respective input formats.

**Comment by erathorn** [comment] 2015-08-20 09:16
@LinguList I am currently working on the rollback (Rollback corrdist refactoring #170). This version works fine. I will try it with the new version. I am pretty sure, that the "strange" behaviour was partly due to my misunderstanding of the threshold, i.e. as to my wrong interpretation, a low value would have made it easier to cluster words. I would suggest to clarify this with an additional line in the documentation. The pickled results may then have interfered a new clustering with another threshold. 

I think this issue can be settled now and I will close this thread.

Thank you all for your help!

P.S. I corrected the lines you mentioned above (etym_dict etc.).

**Closed** 2015-08-20 09:16 UTC
