### ISSUE TITLE
Error in get_scorerer

### ISSUE THREAD

**Issue by erathorn** [lingpy/lingpy#241] opened 2016-04-28 11:41 UTC
I used the newest github version to do some cognate classification using Lingpy.
These are the statements I use.
```
lingpy.rc(schema="asjp")
cognates = lingpy.LexStat("wordlist_2804.wl", check=True)
cognates.get_scorer(method='markov', preprocessing=False)
```
This produces the following error:

```
Traceback (most recent call last):
  File "CognateLingpy.py", line 77, in <module>
    cognates.get_scorer(method='markov', preprocessing=False)
  File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 779, in get_scorer
    self._corrdist = self._get_corrdist(**kw)
  File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 489, in _get_corrdist
    [self[pair, self._weights] for pair in pairs],
  File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 391, in __getitem__
    if idx in self._cache:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by xrotwang** [comment] 2016-04-28 11:53
Hm. This is a numpy error (and one I cannot reproduce). Which numpy version are you on?

**Comment by xrotwang** [comment] 2016-04-28 12:01
@erathorn could you print or dump `self._cache` at the point this error happens?

**Comment by erathorn** [comment] 2016-04-28 12:02
Im using numpy '1.9.2'

**Comment by LinguList** [comment] 2016-04-28 12:35
If possible, @erathorn, please submit your input data as well, and please also try this:

>>> lex = LexStat('yourdata', check=True)

and one mor ething:

lexstat has a bug that we still need to fix, if you don't submit it the tokenized entries for ASJP values in yoru data. That means: tokenize the wrods before hand in a wordlist, using the function asjp2tokens:
```python
>>> from lingpy.sequence.sound_classes import asjp2tokens
>>> wl = Wordlist('yourdata')
>>> wl.add_entries('tokens', 'ipa', lambda x: asjp2tokens)
>>> lex = LexStat(wl, segments='tokens', check=True)
```

etc.

This might help. We still have this problem, and need to fix it: if you change the schema, the tokenization function is still ipa2tokens, which is of course nto what you want to use if you use asjp data.

**Comment by LinguList** [comment] 2016-04-28 12:36
sorry: you already checked, I didn't know.

Now, if possible, please also add parts of your input data, so we can try to replicate.

**Comment by erathorn** [comment] 2016-04-28 12:46
The data is submitted in the following format, so I took care of the tokenization. I am still waiting for lingpy to output the value of `self._cache` at the time of error. But it is painfully slow for more then 120000 items.
```
ID	concept	ipa	doculect	TOKENS
1	Auge::N	ok	ron	o k
2	Auge::N	c3st	oss	c 3 s t
```

**Comment by LinguList** [comment] 2016-04-28 12:53
okay, so I suggest you don't use the markov method, in a first instance. This method is barely tested and usually performs worse than the other methods. Furthermore, if you have a limited string-space in your data, it may fail to produce new strings, and this will lead to an overflow.

We will still need to look into the markov code and see how we can optimize the behaviour, but in general, it is dangerous to use it.

Furthermore, to make it less slow:

reduce the number of runs:
```python
>>> lex.get_scorer(runs=100)
```
or even less. This will also help (as a default, lexstat tries to produce 10000 strings out of yoru input data, created by markov chains, no wonder this takes long, especially when, as I am afraid, the input data is not enough to produce new strings.

One more thing: could you output the following info on your wordlist:

```python

>>> wl.width, wl.height
>>> wl.coverage()
```
I'd like to know, how many concepts and languages you have in your sample.

**Comment by erathorn** [comment] 2016-04-28 14:08
So no I know what takes so long. Data correction is pretty slow for this amount of data.
width: 103
height: 1016

**Comment by erathorn** [comment] 2016-04-28 14:21
@xrotwang Is there a way to get the `self._cache` at the point of error. Just `print(self._cache)` prints the cache everytime `__getitem__` gets called... and this happens very often.

**Comment by LinguList** [comment] 2016-04-28 14:23
@erathorn,

did you already modify settings, as recommended?

Did you test with less languages and smaller lists, and does the error
repeat? I think all this might actually help to get a better hand on the
problem...

**Comment by xrotwang** [comment] 2016-04-28 14:24
@erathorn Maybe try the line above in the stacktrace:
```
 File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 489, in _get_corrdist
```

**Comment by erathorn** [comment] 2016-04-28 14:52
@LinguList I get the same error using `shuffle'. Reducing the height or width did not help either.

**Comment by erathorn** [comment] 2016-04-28 15:13
@xrotwang I have the content of the `self._cache` now as a 14MB .txt file.

**Comment by erathorn** [comment] 2016-04-28 15:48
Okay. I reduced the amount of concepts in my first trial by 50%. This did not solve the error. I know reduced it even more and got it to work for 58 languages and 70 concepts. This suggests to me some kind of problem with the memory handling.
This were the settings:
`cognates.get_scorer(preprocessing=False, runs=100)`

**Comment by LinguList** [comment] 2016-04-28 19:19
strange strange: the cache error implies that for some reason, the cache was transformed to a numpy array, if this is true. 

Here's the lingpy code where the error lies function __getitem__ in lexstat.py:

```python
    def __getitem__(self, idx):
        if idx in self._cache:
            return self._cache[idx]

        if idx in self._data:
            self._cache[idx] = self._data[idx]
            return self._cache[idx]

        try:
            return (
                self._data[idx[0][0]][self._header[self._alias[idx[1]]]],
                self._data[idx[0][1]][self._header[self._alias[idx[1]]]])
        except:
            try:
                # return data entry with specified key word
                self._cache[idx] = self._data[idx[0]][self._header[self._alias[idx[1]]]]
                return self._cache[idx]
            except KeyError:
                return 
```

In this code, there is a check whether the lexstat class-cache contains stuff, but the error that is thrown is a numpy-array error, that always occurs when you ask whether something is in a numpy error:

```python
>>> a = np.array([1,2,3,4])
>>> a in [1,2]
ValueError                                Traceback (most recent call last)
<ipython-input-14-08aa1bef07f3> in <module>()
----> 1 a in [1,2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Now, this means, that the value that was checked whether it is in the cache or not, is a numpy array. Yet this is strange to me, since it is tuples that are passed to the getitem method, and I don't know, where a np.array should've been produced in the code.

I'd suggest, if it doesn't take too long, to try and trigger the output of the stuff that is passed to the getitem method in lingpy (starting from line 384 in lexstat.py), just try to spell out the stuff that is actually transferred there. 

BTW: reducing numpy-code is one thing that would be good for the wordlist class and it's dependents, as I just documented in #242.

**Comment by xrotwang** [comment] 2016-04-29 06:53
Yeah, there's not too many `np.array`s left in the code. I do think, though, that a couple of `assert` statements, in particular when putting something in the cache or assigning attributes or looking things up wouldn't hurt.

**Comment by LinguList** [comment] 2016-04-29 06:54
maybe even just get rid of the cache completely? I was afraid of the
performance, when I first integrated it, but I have the impression, that
I was just mistaken, and that it does not take that long to look things
up...

**Comment by xrotwang** [comment] 2016-04-29 07:39
Yes! I'm totally for getting rid of the cache! It's just an added level of indirection that makes debugging things much harder.

**Comment by LinguList** [comment] 2016-05-02 20:30
Okay, important update! My linux computer just finisched the scoring, in the script, I am at the print-output "made clusters", now it is writing (takes a long time, not finished, who knows when), the whole tsv-script to file. 
This script, if it won't break, should contain also the scorer that was computed.

No idea why this would break on your machine. And I still don't know whether the output will be written , since it seems to require large memory resources (although astonishing, since we handled more than 52 languages, and ASJP alphabet is maximally 40 letters times number of languages times number of prosodic positions), but I can't replicate the bug with numpy 1.11. Note, however, that I don't believe that the bug is related to numpy versions, since it claims that wrong values were passed to the __getitem__ function of lexstat objects, which should never involve lingpy.

I mentioned in an email the importance of cleaning the cache. I just added this as issue #246

**Comment by LinguList** [comment] 2016-05-02 20:53
A question in the line of this bug, but with more general implications:

LingPy currently often creates strings, assembles them, and then writes stuff to file. Is this in some way a no-go? I just realise, when waiting for the stuff to be written to file (with 1.7 GB in memory), that it might well be a bad idea to do so, since LingPy is apparently still creating the string for the scorer, but not writing to file yet. If this is problematic, we should

* find a way to handle the scorers, which we want to keep once computed, but less memory-demanding, and
* change file writing (but this is a general thing: using mako, etc., to get rid of the current inline statements)

The general question here relates to #227, and what I am asking myself and the others is: is it recommended to first produce a string, or to find ways to immediately write things to files, or to serialize them in smarter ways? A scorer (which is just getting very big in @erathorn's data, is in the end just a python dictionary...

**Comment by LinguList** [comment] 2016-05-03 07:03
Okay, code runs without problems on both py3 and py2. Interestingly, it seems to be WAY faster on py3.

Numpy-version is NOT a problem, since I tested on another computer with numpy version 1.8.2. 

@erathorn, could you try to redue your analysis with py3?, and please don't forget to clean the cache, which should be in some directory cache/lingpy (the typical "home" on windows, in case you use windows).

We still have, however, the problem of writing to file with big dictionaries. Here, I tested only the py2 version and it took ages, so that I stopped in the end. As a general tip for @erathorn, if you are not interested in the scorers in text file after calling get_scorer, you could:

```python
>>> lex.pickle() # to make sure the scorer is stored
>>> lex.output('tsv', prettify=False, ignore="all")
```
this only outputs the columns, not the stuff around, like the scorer, and the file will be smaller. If you want to output only certain columns, you can specify a keyword.

More information is in the output-function of wordlists:

http://lingpy.readthedocs.io/en/latest/reference/lingpy.basic.html#lingpy.basic.wordlist.Wordlist.output

**Comment by erathorn** [comment] 2016-05-03 09:05
Ok. I deleted the cache and reinstalled lingpy. The next run of the script lingpy raises a UnicodeError.
Cleaning the cache without reinstalling lingpy got me the same error as before. I will try python 3 now.

```
C:\Python27\lib\pprint.py:82: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return sorted(iterable)
Traceback (most recent call last):
  File "D:/EVOLAEMP/jwahle/ProfileHMM/CognateLingpy.py", line 88, in <module>
    cognates.get_scorer(preprocessing=False, runs=100)
  File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 791, in get_scorer
    self._corrdist = self._get_corrdist(**kw)
  File "C:\Python27\lib\site-packages\lingpy-2.4-py2.7.egg\lingpy\compare\lexstat.py", line 496, in _get_corrdist
    pprint.pprint(self._cache)
  File "C:\Python27\lib\pprint.py", line 59, in pprint
    printer.pprint(object)
  File "C:\Python27\lib\pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "C:\Python27\lib\pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "C:\Python27\lib\pprint.py", line 233, in _repr
    self._depth, level)
  File "C:\Python27\lib\pprint.py", line 245, in format
    return _safe_repr(object, context, maxlevels, level)
  File "C:\Python27\lib\pprint.py", line 287, in _safe_repr
    for k, v in _sorted(object.items()):
  File "C:\Python27\lib\pprint.py", line 82, in _sorted
    return sorted(iterable)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 0: ordinal not in range(128)
```

**Comment by erathorn** [comment] 2016-05-03 09:16
I got the same error using python 3.4

```
Traceback (most recent call last):
  File "C:/Users/Johannes/test/lptest.py", line 88, in <module>
    cognates.get_scorer(preprocessing=False, runs=100)
  File "C:\Python34\lib\site-packages\lingpy-2.4-py3.4.egg\lingpy\compare\lexstat.py", line 791, in get_scorer
    self._corrdist = self._get_corrdist(**kw)
  File "C:\Python34\lib\site-packages\lingpy-2.4-py3.4.egg\lingpy\compare\lexstat.py", line 501, in _get_corrdist
    [self[pair, self._weights] for pair in pairs],
  File "C:\Python34\lib\site-packages\lingpy-2.4-py3.4.egg\lingpy\compare\lexstat.py", line 501, in <listcomp>
    [self[pair, self._weights] for pair in pairs],
  File "C:\Python34\lib\site-packages\lingpy-2.4-py3.4.egg\lingpy\compare\lexstat.py", line 399, in __getitem__
    if idx in self._cache:
|
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by LinguList** [comment] 2016-05-03 09:49
Just to make one thing sure: you use windows, right?

**Comment by erathorn** [comment] 2016-05-03 09:50
Yes, I do.


Am 03.05.2016 um 11:49 schrieb Johann-Mattis List:

**Comment by LinguList** [comment] 2016-05-03 10:05
well, the unicode error is due to yoru pprint-statement. you should remove this, it want's to print out the cache.

Please try the following patch in lexstat.py, rewrite function __getitem__ as follows:

```python

    def __getitem__(self, idx):
        """
        Method allows quick access to the data by passing the integer key.

        In contrast to the basic wordlist, the LexStat wordlist further allows
        to access item pairs by passing a tuple.
        """

        if idx in self._data:
            return self._data[idx]

        try:
            return (
                self._data[idx[0][0]][self._header[self._alias[idx[1]]]],
                self._data[idx[0][1]][self._header[self._alias[idx[1]]]])
        except:
            try:
                # return data entry with specified key word
                return self._data[idx[0]][self._header[self._alias[idx[1]]]]
            except KeyError:
                return 
```

this ignores the cache and prevents that the cache is written in lexstat.py, if this works, we'll use this code in the future, since the cache shall anyway be replaced.

if it does not work, debug by printing the index "idx" that is passed by the getitem function, and paste the results, this will give some more insights into what is actually going on.

**Comment by erathorn** [comment] 2016-05-03 13:02
This version of `getitem` does the trick for python 2.7 and 3.4!

**Comment by LinguList** [comment] 2016-05-03 13:04
coooool!

This means that this bug in here will be automatically also closed once we remove the cache in future lingpy updateds, as indicated in #245 

closing this now, but please make sure to keep the patch until #245 is officially fixed.

**Closed by LinguList** 2016-05-03 13:04 UTC
Labels: bug
